project:
  type: website
  output-dir: docs

website:
  title: "SDS290"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: mp_1.qmd
        text: Mini Project 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

