project:
  type: website
  output-dir: docs

website:
  title: "SDS290"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

