project:
  type: website
  output-dir: docs

website:
  title: "SDS290"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Mini Projects
        menu:
        - href: mp_1.qmd
          text: Mini Project 1
        - href: mp_2.qmd
          text: Mini Project 2
      - href: homework.qmd
        text: Homework
      - text: Trouble shooting links
        menu:
        - href: https://smithcollege-sds.github.io/sds100/lab_01_setup.html
          text: Downloading R and RStudio
        - text: Basics of Data Wranging in R
          href: https://smithcollege-sds.github.io/sds100/lab_04_wrangling.html
        - text: Troubleshooting R Markdown
          href: https://smithcollege-sds.github.io/sds-www/rmarkdown_problems.html
        - text: Qualtrics
          href: https://smithcollege.qualtrics.com/
      - text: Lecture Slides
        menu:
        - href: lectures/welcome.pptx
          text: Intro Slides
        - href: https://docs.google.com/presentation/d/1VTK8NSOe8LNvLdNWxIxqalFhHsyXeDjUsibJvS0T_Bw/edit?usp=sharing
          text: Week 2 Anova
        - href: https://docs.google.com/presentation/d/18F-4kaERjzFcEn8gkLgQoAp42q2ItlIo/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 3 Anova 
        - href: https://docs.google.com/presentation/d/192UZsHdQ98lzpaQq7Pc8KR0V13kJHtBc/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Mini Project 1 Overview
        - href: https://docs.google.com/presentation/d/19DS63YGdewwpJ4dfG9KnXxX0b-FwePLk/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 4 Anova
        - href: https://docs.google.com/presentation/d/1AILjruu0m3gjvjVjLcpBn2NwNBhj3rNg/edit?usp=sharing&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 5 Experimental Design
        - href: https://docs.google.com/presentation/d/1Bv9A9_tNmB2crI2ygWVn6rAP7j6udZqD/edit?usp=share_link&ouid=105141350110500354644&rtpof=true&sd=true
          text: Week 6 Two Way Anova
      - text: Sample Code
        href: sample_code.qmd
  

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

