---
title: "Schedule"
---

Please read the specified sections *before* class that day.

::: past
:::

<!--closing "past" div-->

<div class="row">

::: {.col-md-3 .past}
#### Tue, Jan 24

-   No class

    </div>

    <div class="col-md-3 past">

    #### Wed, Jan 25

-   No class

    </div>

    <div class="col-md-3 past">

    #### Thurs, Jan 26

-   Introduction to the course

-   Four-step process

-   [Short experiment](https://smithcollege.qualtrics.com/jfe/form/SV_71nqdhEpN8frd6B)

-   Homework:

    -   HW #1a: record your name on Moodle
    -   HW #1b: CITI training

    </div>

    <div class="col-md-3 past">

    #### Fri, Jan 27

-   Homework due today:

    -   Read **Stat2** Ch. 0 (PDF on Moodle)
    -   **HW #1a due today at 11:55p**

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Jan 31

-   One-way ANOVA

-   Homework due today:

    -   Read **Stat2** Ch. 5.1-5.2

    </div>

    <div class="col-md-3 past">

    #### Wed, Feb 1

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Feb 2

-   One-way ANOVA (cont.)

-   Homework due today:

    -   Read **Stat2** Ch. 5.3

-   Office hours: 1:20-2:35p

    </div>

    <div class="col-md-3 past">

    #### Fri, Feb 3

-   Homework due today:

    -   **HW #1b and #1c due today at 11:55p**

-   Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Feb 7

-   Inference for ANOVA

-   Homework due today:

    -   Read **Stat2** Ch. 5.4

    </div>

    <div class="col-md-3 past">

    #### Wed, Feb 8

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Feb 9

-   ANOVA Conditions

-   MP1 assignment

-   Homework due today:

    -   No reading for today

-   Office hours: 1:20-2:35p

    </div>

    <div class="col-md-3 past">

    #### Fri, Feb 10

-   Homework due today:

    -   **HW #2 due today at 11:55p**

-   Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Feb 14

-   Confidence intervals and effect sizes

-   Transformations

-   MP1 topics

-   Homework due today:

    -   Brainstorm topics for MP1
    -   Read **Stat2** Ch. 5.5-5.6

    </div>

    <div class="col-md-3 past">

    #### Wed, Feb 15

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Feb 16

-   Multiple comparisons

-   Introduction to Qualtrics

-   Homework due today:

    -   Find potential stimuli (images) for MP1
    -   Read **Stat2** 4.5 (up to, not including, example 4.10)
    -   Read **Stat2** 5.7

-   Office hours: 1:20-2:35p

    </div>

    <div class="col-md-3 past">

    #### Fri, Feb 17

-   Homework due today:

    -   **HW #3 due on today at 11:55p**

-   Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Feb 21

-   Four basic designs

-   Time to work on MP1

-   Homework due today:

    -   Read **Cobb** Ch. 1.1-1.3 (PDF on Moodle)

    </div>

    <div class="col-md-3 past">

    #### Wed, Feb 22

-   Office hours **on Zoom only**: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Feb 23

-   **Class cancelled**

-   Office hours **on Zoom only**: 1:20-2:35p

    </div>

    <div class="col-md-3 past">

    #### Fri, Feb 24

-   Homework due today:

    -   **HW #4 due on today at 11:55p**

-   Zoom office hours: 1:30-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Feb 28

-   Blocking

-   Homework due today:

    -   Read **Stat2** Ch 6.1-6.2

    </div>

    <div class="col-md-3 past">

    #### Wed, March 1

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, March 2

-   Fitting the model for a block design

-   Homework due today:

    -   Read Ch **Stat2** 6.3

    </div>

    <div class="col-md-3 past">

    #### Fri, March 3

-   Homework due today:

    -   **MP1 Qualtrics survey due for pre-approval by 11:55p**

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, March 7

-   **Fall break**

    </div>

    <div class="col-md-3 past">

    #### Wed, March 8

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, March 9

-   MP1 Data Collection Day

-   Assessing the block design

-   Using the block design

-   Homework due today:

    -   Read Ch **Stat2** 6.4-6.5

    </div>

    <div class="col-md-3 past">

    #### Fri, March 10

-   Homework due today:

    -   **HW #5 due tonight at 11:55p**

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, March 14

-   Review for Exam 1

-   Analysis of MP1 data

    </div>

    <div class="col-md-3 past">

    #### Wed, March 15

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, March 16

-   **Time to work on Exam 1**

    </div>

    <div class="col-md-3 past">

    #### Fri, March 17

-   Homework due today:

    -   **Exam 1 due tonight at 11:55p**

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Oct 26

-   Interactions

-   Two-way factorial designs

-   Homework due today:

    -   Read Ch **Stat2** 7.1-7.2

    </div>

    <div class="col-md-3 past">

    #### Wed, Oct 27

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Oct 28

-   Fitting two-way ANOVA

-   Practice designs

-   Homework due today:

    -   Read Ch **Stat2** 7.3

    </div>

    <div class="col-md-3 past">

    #### Fri, Oct 29

-   Homework due today:

    -   **Mini Project 1 due 11:55p** (upload to Moodle by Midnight)

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Nov 2

-   Fitting two-way design

-   Practice designs

-   Homework due today:

    -   Read Ch **Stat2** 7.4

    </div>

    <div class="col-md-3 past">

    #### Wed, Nov 3

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Nov 4

-   **Cromwell Day - Class cancelled**

    </div>

    <div class="col-md-3 past">

    #### Fri, Nov 5

-   Homework due today:

    -   [**HW #6 due today at 11:55p**](homework.html)

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Nov 9

-   Assessing two-way design

-   Practice designs

-   Homework due today:

    -   Read Ch **Stat2** 7.5

    </div>

    <div class="col-md-3 past">

    #### Wed, Nov 10

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Nov 11

-   Chapter 7 catch-up

-   MP2 group assignments

-   Homework due today:

    -   No reading

    </div>

    <div class="col-md-3 past">

    #### Fri, Nov 12

-   Homework due today:

    -   [**HW #7 due thurs at 11:55p**](homework.html)

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Nov 16

-   MP2 project work time

-   Homework due today:

    -   Read Ch **Stat2** 8.1 - 8.2

    </div>

    <div class="col-md-3 past">

    #### Wed, Nov 17

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Nov 18

-   Multiple tests

-   Inference Test for S Condition

-   Repeated measures designs

-   Homework due today:

    -   Read Ch **Stat2** 8.6
    -   [Fisher's history of racism](https://en.wikipedia.org/wiki/Ronald_Fisher#Eugenics)\

    </div>

    <div class="col-md-3 past">

    #### Fri, Nov 19

-   Homework due today:

    -   [**HW #8 due today at 9:20a**](homework.html)

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Nov 23

-   MP2 project work time

-   Repeated measures designs

-   Homework due today:

    -   Read Ch **Stat2** 8.4
    -   **MP2 Pre-approval due tonight 11:55p**

    </div>

    <div class="col-md-3 past">

    #### Wed, Nov 24

-   **Thanksgiving break**

    </div>

    <div class="col-md-3 past">

    #### Thurs, Nov 25

-   **Thanksgiving break**

    </div>

    <div class="col-md-3 past">

    #### Fri, Nov 26

-   **Thanksgiving break**

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: {.col-md-3 .past}
#### Tue, Nov 30

-   MP2 Data Collection

-   Repeated measures designs (cont.)

-   Homework due today:

    -   Read Ch **Stat2** 8.6

    </div>

    <div class="col-md-3 past">

    #### Wed, Dec 1

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3 past">

    #### Thurs, Dec 2

-   MP2 Data Analysis

-   Design Practice

-   Homework due today:

    -   Read Ch **Stat2** 8.7-6.8

    </div>

    <div class="col-md-3 past">

    #### Fri, Dec 3

-   Homework due today:

    -   [**HW #9 due today at 9:20a**](homework.html)

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: col-md-3
#### Tue, Dec 7

-   Review for Exam 2

    </div>

    <div class="col-md-3">

    #### Wed, Dec 8

-   Office hours: 10:50-12:05p

    </div>

    <div class="col-md-3">

    #### Thurs, Dec 9

-   **Exam 2 work time**

    </div>

    <div class="col-md-3">

    #### Fri, Dec 10

-   Homework due today:

    -   **Exam 2 due tonight at 11:55p**

-   Zoom office hours: 12:15-3:00p [book here](https://randigarcia.youcanbook.me)

    </div>
:::

------------------------------------------------------------------------

<div class="row">

::: col-md-3
#### Tue, Dec 14

-   **Finals week**

    </div>

    ::: col-md-3
    #### Wed, Dec 15
    :::

    ::: col-md-3
    #### Thurs, Dec 16
    :::

    <div class="col-md-3">

    #### Fri, Dec 17

-   **MP2 due today at 11:55p**

    </div>
:::
